Repository UMLCloudComputing/UMLCloudComputing.github.io, pull requests merged in 2024-09, with the labels that each got.

#84 chore/Add semester welcome blog, update dependencies, updated banner
  blog/Welcome to the Cloud Computing Club.mdx
  blog/authors.yml
  blog/tags.yml
  docs/resources/welcome.md
  docusaurus.config.js
  package-lock.json
  package.json
Labels: blog_update

#85 quickfix: Add missing bullet points to Our Projects section
  blog/Welcome to the Cloud Computing Club.mdx
Labels: quickfix

#86 chore: Update banner to kick-off meeting info
  .gitignore
  docusaurus.config.js
Labels: schedule update

#88 chore: Minor update to webpage banner
  docusaurus.config.js
Labels: documentation

#89 Chore/update readme
  README.md
Labels: documentation

#90 chore: Replace boldface to inline code for readme
  README.md
Labels: documentation

#91 fix: Correction to readme admonition
  README.md
Labels: documentation

#92 fix: Admonition correction attempt #2
  README.md
Labels: documentation

#93 fix: Fix Admonition issue sourced from details tags
  README.md
Labels: documentation

#94 fix: Readme text sizing issue
  README.md
Labels: documentation

#95 feat: Add meeting notes section
  docs/schedule/2024Fall/2024Fall.md
  docs/schedule/2024Fall/Meet1Notes.md
Labels: documentation

#96 Updates to the schedule
  docs/schedule/2024Fall/2024Fall.md
  docs/schedule/2024Fall/Meet1Notes.md
  docs/schedule/2024Fall/Week10.md
  docs/schedule/2024Fall/Week11.md
  docs/schedule/2024Fall/Week12.md
  docs/schedule/2024Fall/Week13.md
  docs/schedule/2024Fall/Week14.md
  docs/schedule/2024Fall/Week15.md
  docs/schedule/2024Fall/Week2.md
  docs/schedule/2024Fall/Week3.md
  docs/schedule/2024Fall/Week4.md
  docs/schedule/2024Fall/Week5.md
  docs/schedule/2024Fall/Week6.md
  docs/schedule/2024Fall/Week7.md
  docs/schedule/2024Fall/Week8.md
  docs/schedule/2024Fall/Week9.md
Labels: documentation, enhancement

#98 feat: Minor color palate changes
  src/css/custom.css
Labels: enhancement

#99 chore: Slug updates to be more concise
  docs/activities/welcome.md
  docs/projects/welcome.md
  docs/resources/welcome.md
  src/pages/index.js
Labels: documentation

#100 docs: add comp 2 exam 2 study guide
  docs/resources/UML Class Resources/COMP.1020 - Computing II/Exam Study Materials/Exam 2 Study Guide.mdx
Labels: documentation

#102 chore: Added a more members to landing page
  src/components/AvatarLarge.tsx
  src/members_meta/members.json
Labels: enhancement

#103 chore/add meeting notes
  docs/schedule/2024Fall/Week2.md
  docs/schedule/2024Fall/Week2.mdx
  package.json
  src/pages/index.js
  static/img/meeting-notes/pizza-as-a-service.jpg
Labels: documentation

#104 quickfix: Correction to random content in notes
  docs/schedule/2024Fall/Week2.mdx
Labels: quickfix

#105 chore: Revert back to season-year based slug for notes to avoid future slug misdirects and 404s (first tech-debt)
  docs/schedule/2024Fall/2024Fall.md
  docs/schedule/2024Fall/Week10.md
  docs/schedule/2024Fall/Week11.md
  docs/schedule/2024Fall/Week12.md
  docs/schedule/2024Fall/Week13.md
  docs/schedule/2024Fall/Week14.md
  docs/schedule/2024Fall/Week15.md
  docs/schedule/2024Fall/Week2.mdx
  docs/schedule/2024Fall/Week3.md
  docs/schedule/2024Fall/Week4.md
  docs/schedule/2024Fall/Week5.md
  docs/schedule/2024Fall/Week6.md
  docs/schedule/2024Fall/Week7.md
  docs/schedule/2024Fall/Week8.md
  docs/schedule/2024Fall/Week9.md
  docs/schedule/readme
Labels: bug, schedule update, meeting notes update

#106 Feat/add local search
  .github/pull_request_template.md
  README.md
  docusaurus.config.js
  package-lock.json
  package.json
Labels: enhancement

#107 chore/Meeting Schedule Updates as per speaker comms
  .vscode/settings.json
  docs/schedule/2024Fall/2024Fall.md
  docs/schedule/2024Fall/Week2.mdx
  docs/schedule/2024Fall/Week3.md
  docs/schedule/2024Fall/Week4.md
  docs/schedule/2024Fall/Week5.md
  docs/schedule/2024Fall/Week6.md
Labels: schedule update

#109 Chore/meeting notes
  docs/schedule/2024Fall/Week3.md
Labels: meeting notes update

#110 chore: Added meeting video iframes
  docs/schedule/2024Fall/Week2.mdx
  docs/schedule/2024Fall/Week3.mdx
  src/css/custom.css
Labels: meeting notes update

#111 Chore/landing page edit
  docusaurus.config.js
  src/css/custom.css
  src/pages/index.js
Labels: enhancement

#112 feat: Reorganized Info cards on landing page
  src/cards_meta/cards_data.json
  src/components/PaperCard.tsx
  src/css/custom.css
  src/pages/index.js
Labels: enhancement

#113 Fix/remove mobile bottom navbar
  src/css/custom.css
  src/theme/Navbar/MobileSidebar/Header/index.js
  src/theme/Navbar/MobileSidebar/Layout/index.js
  src/theme/Navbar/MobileSidebar/PrimaryMenu/index.js
  src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
  src/theme/Navbar/MobileSidebar/Toggle/index.js
  src/theme/Navbar/MobileSidebar/index.js
Labels: enhancement

#114 fix: Correct footer css to be more specific
  src/css/custom.css
Labels: quickfix

#115 Chore/update member modals
  src/components/AvatarLarge.tsx
  src/members_meta/members.json
Labels: enhancement

#116 chore: Added Youtube to socials dropdown
  docusaurus.config.js
Labels: documentation

#117 Fix/ Correct Meta data for cards and member to be static
  docusaurus.config.js
  src/pages/index.js
  static/meta_data/cards_meta/cards_data.json
  static/meta_data/members_meta/members.json
Labels: bug, quickfix

#118 Fix/correct meeting iframe links
  docs/schedule/2024Fall/Week2.mdx
  docs/schedule/2024Fall/Week3.mdx
  src/css/custom.css
Labels: bug, enhancement, quickfix

#119 fix: Rename iframe contianer CSS class to avoid styling collisions wi…
  docs/schedule/2024Fall/Week2.mdx
  docs/schedule/2024Fall/Week3.mdx
  src/css/custom.css
Labels: bug, quickfix

#120 Chore/update meeting notes
  docs/schedule/2024Fall/Week3.mdx
  docs/schedule/2024Fall/Week4.md
  docs/schedule/2024Fall/Week4.mdx
Labels: meeting notes update

#121 quickfix: Formatting edits to Week 4 meeting notes
  docs/schedule/2024Fall/Week3.mdx
  docs/schedule/2024Fall/Week4.mdx
Labels: meeting notes update
